#pragma once

#include "cocos2d.h"

#define DISPLAY_TIME_SPLASH_SCENE 2
#define TRANSITION_TIME 0.5
#define PIPE_SPAWN_FREQUENCY 1.5
#define PIPE_GAP 10

#define UPPER_SCREEN_PIPE_THRESHOLD 0.90
#define LOWER_SCREEN_PIPE_THRESHOLD 0.1
#define PIPE_MOVEMENT_SPEED 0.01


#define LEFT_BUTTON_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
const int BIRD_COLLISION_BITMASK = 1;